acsone/acsone-odoo-project-template

src/.bumpversion.cfg.jinja, src/README.md.jinja
This is to be able to do 'git push --follow-tags' instead of 'git push && git push --tags' (one command instead of two)
=> [IMP] add tag message in bumpversion to be able to do: git push --follow-tags

src/.pre-commit-config.yaml.jinja, src/Dockerfile.jinja, src/README.md.jinja, src/pyproject.toml.jinja, src/requirements-build.txt.in
- enable the pip cache in Dockerfile, for faster local builds
- use build constraints instead of build isolation
- add xmlsec build dependencies
- split the requirements in the Dockerfile instead of a pip-df post sync command (since this splitting is only necessary as a performance optimization for the Dockerfile): this avoid polluting the source with the requirement-groups*.txt
@acsone/acsone-odoo-team
=> Improve Dockerfile

src/.gitlab-ci.yml.jinja
Module tags must start with / (see odoo --help)
@acsone/acsone-team
=> ci: refine the --test-tags option

src/.isort.cfg
We don't need this anymore since we use ruff.
=> Remove useless isort config

src/pyproject.toml.jinja
Ruff doesn't like mutable class variables but Odoo uses lists for _inherit, _sql_constraints,...
=> [IMP] pyproject.toml: Ignore RUF012

src/.pre-commit-config.yaml.jinja, src/.prettierrc.cjs, src/.prettierrc.yml
More information at https://github.com/prettier/plugin-xml/issues/478
Due to a weird interaction between pre-commit and the prettier plugin loading mechanism we need to change the prettier configuration format from yaml to cjs.
=> Improve xml autoformatter

src/Dockerfile.jinja
The odoo-bedrock now includes the Ubuntu distro name in its tag.
=> Update base image

src/container/entrypoint-dbbase.jinja
- fs_attachment instead of attachment_s3
- exponential backoff when checking for kwkhtmltopdf availability
- wait for postgres readiness
=> A few improvements to the container entrypoint

src/pyproject.toml.jinja
This is supported by pip-deepfreeze 2.0+, and useful to ensure the team share pip-df features.
=> Declare minimum pip deepfreeze version

copier.yml, src/.gitlab-ci.yml.jinja
Printing tests require HttpCase so CSS assets are available.
=> Enable kwkhtmltopdf in tests

src/.gitlab-ci.yml.jinja
Small fix: I think that the declartion of services has been too much indented.
=> [FIX] gitlab-ci.yml: declaration of services - adjust indents

src/odoo/addons/server_environment_files/test/test.conf, src/odoo/addons/server_environment_files/uat/uat.conf
Default value for check_connection_method is marker_file, but this doens't work without write access.
Our test and uat env usually have read only access to the prod storage.
In our case, we don't really need to check the connection anyway.
See https://github.com/OCA/storage/pull/357
=> Fix fs_storage check_connection_method for readonly fsprod

src/requirements-build.txt.in
Since hatchling 1.22.4, editables is not a hard dependency, (it is provided by the get_requires_for_build_editable hook (https://github.com/pypa/hatch/pull/1255). We need to add it as a build dependency.
=> [ADD] requirements-build: editables dependency

src/checklog-odoo.cfg
The previous name `checklog` is ignored and should be `checklog-odoo`
=> [FIX] rename the section of checklog-odoo

src/requirements.txt.in.jinja
For versions >=17 one must use the pyproject.toml inside the addon repo
=> [UPD] requirements.txt.in: patched OCA addons helper

src/pyproject.toml.jinja
It parses xlsx with openpyxl which is a hard dependency of Odoo.
=> Odoo 18 supports the latest xlrd

src/.gitlab-ci.yml.jinja
This distinction did not show any practical benefit. When significant changes are needed in test and
we want to keep the prod deployment unchanged it is easier to create a dedicated branch for that.
=> Stop using different deploy-test and deploy-prod branches

src/eslint.config.cjs.jinja
Avoid eslint raising ` Invalid JSDoc tag name "odoo-module"  jsdoc/check-tag-names` for tag `odoo-module` that is needed for Odoo versions <18.
=> [FIX] estlint.config.cjs: allow tag odoo-module for Odoo versions < 18.

src/.gitlab-ci.yml.jinja
To access source repos, we now have a group level key that is used by default.
=> Reduce reliance on SSH_DEPLOY_KEY

src/.pre-commit-config.yaml.jinja, src/container/entrypoint-dbbase.jinja, src/odoo/addons/{{ project_trigram }}_fs_attachment/__manifest__.py.jinja
These checks are not supported by OVH S3, apparently.
And other minor updates.
=> Minor tweaks, constrain fsspec version

copier.yml, src/Dockerfile.jinja
This is important to have a different pip cache per distro, since, for instance, some C libraries we build declare their minium required GLIBC version.
Documentation for cache mounts: https://docs.docker.com/reference/dockerfile/#run---mounttypecache
=> Scope pip cache per base distro

src/container/entrypoint-dbbase.jinja, src/pyproject.toml.jinja
Take advantage of the new click-odoo-initdb features to
- work when the odoo db is pre-created and empty (which is the case with cnpg).
- store attachments in db while disabling the cache
=> Improve entry point
